### ISSUE TITLE
Add support for bcg729 1.0.2+

### ISSUE THREAD

**Issue by urobasa** [LubosD/twinkle#104]
cmake .. -DWITH_ALSA=On -DWITH_SPEEX=On -DWITH_ILBC=Off -DWITH_ZRTP=Off -DWITH_G729=On -DWITH_QT5=On

/home/admins/twinkle/src/audio/audio_decoder.cpp: In member function ‘virtual uint16 t_g729a_audio_decoder::decode(uint8*, uint16, int16*, uint16)’:
/home/admins/twinkle/src/audio/audio_decoder.cpp:550:50: error: invalid conversion from ‘int16* {aka short int*}’ to ‘uint8_t {aka unsigned char}’ [-fpermissive]
   bcg729Decoder(_context, &payload[done], false, &pcm_buf[done * 8]);
                                                  ^~~~~~~~~~~~~~~~~~
/home/admins/twinkle/src/audio/audio_decoder.cpp:550:68: error: too few arguments to function ‘void bcg729Decoder(bcg729DecoderChannelContextStruct*, uint8_t*, uint8_t, uint8_t, uint8_t, uint8_t, int16_t*)’
   bcg729Decoder(_context, &payload[done], false, &pcm_buf[done * 8]);
                                                                    ^
In file included from /home/admins/twinkle/src/audio/audio_decoder.h:42:0,
                 from /home/admins/twinkle/src/audio/audio_decoder.cpp:20:
/usr/include/bcg729/decoder.h:68:24: note: declared here
 BCG729_VISIBILITY void bcg729Decoder(bcg729DecoderChannelContextStruct *decoderChannelContext, uint8_t bitStream[], uint8_t bitStreamLength, uint8_t frameErasureFlag, uint8_t SIDFrameFlag, uint8_t rfc3389PayloadFlag, int16_t signal[]);
                        ^~~~~~~~~~~~~
/home/admins/twinkle/src/audio/audio_decoder.cpp: In member function ‘virtual uint16 t_g729a_audio_decoder::conceal(int16*, uint16)’:
/home/admins/twinkle/src/audio/audio_decoder.cpp:565:48: error: invalid conversion from ‘int16* {aka short int*}’ to ‘uint8_t {aka unsigned char}’ [-fpermissive]
  bcg729Decoder(_context, nullptr, true, pcm_buf);
                                                ^
/home/admins/twinkle/src/audio/audio_decoder.cpp:565:48: error: too few arguments to function ‘void bcg729Decoder(bcg729DecoderChannelContextStruct*, uint8_t*, uint8_t, uint8_t, uint8_t, uint8_t, int16_t*)’
In file included from /home/admins/twinkle/src/audio/audio_decoder.h:42:0,
                 from /home/admins/twinkle/src/audio/audio_decoder.cpp:20:
/usr/include/bcg729/decoder.h:68:24: note: declared here
 BCG729_VISIBILITY void bcg729Decoder(bcg729DecoderChannelContextStruct *decoderChannelContext, uint8_t bitStream[], uint8_t bitStreamLength, uint8_t frameErasureFlag, uint8_t SIDFrameFlag, uint8_t rfc3389PayloadFlag, int16_t signal[]);
                        ^~~~~~~~~~~~~
src/audio/CMakeFiles/libtwinkle-audio.dir/build.make:86: ошибка выполнения рецепта для цели «src/audio/CMakeFiles/libtwinkle-audio.dir/audio_decoder.cpp.o»
make[2]: *** [src/audio/CMakeFiles/libtwinkle-audio.dir/audio_decoder.cpp.o] Ошибка 1
CMakeFiles/Makefile2:233: ошибка выполнения рецепта для цели «src/audio/CMakeFiles/libtwinkle-audio.dir/all»
make[1]: *** [src/audio/CMakeFiles/libtwinkle-audio.dir/all] Ошибка 2
Makefile:129: ошибка выполнения рецепта для цели «all»

**Comment by fbriere** [comment]
It would appear that the bcg729 API was changed in version 1.0.2 (specifically by commits BelledonneCommunications/bcg729@843c130  and BelledonneCommunications/bcg729@948d32a).

Until Twinkle supports the new API, you should probably downgrade to 1.0.1, which seems to compile just fine.

**Comment by fbriere** [comment]
I have just submitted PR #152 to fix this issue.

Full disclosure: this code is untested. Of course, it compiles, and the CMake test to find which version is installed is working fine, but I couldn't test the part actually calling bcg729 functions.  Now, the changes are so minimal to make any bug very unlikely.  Still, if other users could give it i try just to confirm it works just fine, that would be appreciated.  Thanks!

**Comment by fbriere** [comment]
@urobasa @DAC324 If you ever get an opportunity to test this fix, that would be most welcome!

**Comment by fbriere** [comment]
> Incompatible API change in a point release? Sigh...

Even better, they did not bother changing the SONAME, even though both versions's ABI are incompatible.  Mixing them results in muted sound at best, and segfaults at worst.

**Comment by fbriere** [comment]
I've now had a chance to actually test G.729, and this seems to work fine.  (Any confirmation would always be welcome, of course.)

**Comment by DAC324** [comment]
Hello all,
unfortunately, Twinkle does not seem to run under Manjaro. 
At first, it does not accept any other settings for audio input or
audio output other than "ALSA default device". If there is any other
device specified, Twinkle complains that it cannot access that device
(no matter if it exists in the system or not). 
Second: As soon as I dial any number, Twinkle emits a loud static noise
through the output device. The very same noise is transmitted by
Twinkle to the recipient of the call after the connection is
established, making a conversation impossible in both directions.
That, unfortunately, makes Twinkle unusable for me, which seems to be
independent of the discussed fix.
inxi-F:
Audio:  Device-1: Intel 6 Series/C200 Series Family High Definition
Audio   driver: snd_hda_intel   Device-2: NVIDIA GF116 High Definition
Audio driver: snd_hda_intel   Device-3: Logitech HD Webcam C525 type:
USB driver: snd-usb-audio,uvcvideo   Sound Server: ALSA v: k5.2.13-1-
MANJARO 
Kind regards,
DAC324
Am Sonntag, den 08.09.2019, 07:31 -0700 schrieb Frédéric Brière:

**Comment by fbriere** [comment]
@DAC324 Unless this only occurs with #152 and not with the `master` branch, please open a separate issue for these unrelated problems.  Thanks.

**Comment by DAC324** [comment]
> I've now had a chance to actually test G.729, and this seems to work fine. (Any confirmation would always be welcome, of course.)

Unfortunately, the code still has not been fixed to compile with any G.729 version newer than 1.0.1. 
With that version, I still get that crackling sound, even when using the master branch.
In Manjaro, version 1.0.4 is available in the repositories for G.729 but unfortunately, Twinkle does not compile against this version (see above) so it is impossible to use it, at least with Manjaro (and I also guess any Arch) Linux.

**Comment by fbriere** [comment]
@DAC324 As I previously said, please open a separate issue for this unrelated problem.  Thanks.
