### ISSUE TITLE
Random segfault

### ISSUE THREAD

**Issue by G3ph4z** [LubosD/twinkle#114]
Hi,

**OS:**   Xubuntu 16.04  - Linux 4.4.0-109-generic 

We have many PC-s with this setup, and only 2 have a problems. 

Twinkle is exiting randomly, no popup, no error, just exit. 

**Syslog:** 
twinkle[3852]: segfault at 161 ip 00007fbd7f5fee94 sp 00007ffe36a89110 error 4 in libspeexdsp.so.1.5.0[7fbd7f5f9000+11000]

**Comment by fbriere** [comment]
If you are on xenial, I assume you are using version 1.9.0?  In that case, could you try version 1.10.1 (packaged for artful and bionic), if possible?

If it still crashes, we would need a detailed backtrace (of either version) to debug this further, with the `twinkle-dbgsym` and `libspeex-dbg` packages installed.  See the Ubuntu Wiki for information about [installing debug packages](https://wiki.ubuntu.com/Debug%20Symbol%20Packages) and [generating a backtrace](https://wiki.ubuntu.com/Backtrace).

Thanks!

**Comment by G3ph4z** [comment]
Yes, we are using 1.9.0. ofc, we can, just please let me 1-2 days.

**Comment by G3ph4z** [comment]
I still cannot acces those PC's, maybe on the next week, but we setted up new ws with Ubuntu 17.10 + Twinkle 1.10.1 and its looks solved.

**Comment by fbriere** [comment]
@G3ph4z Have there been any news on this matter?  Did the issue systematically resolve itself every time Twinkle was upgraded to 1.10.1?

**Comment by fbriere** [comment]
Closing this issue after four years of inactivity.
