### ISSUE TITLE
error 0 in libQt5Widgets.so.5.5

### ISSUE THREAD

**Issue by G3ph4z** [LubosD/twinkle#115]
Hi,

I found another problem.
OS:  Xubuntu 16.04 - Linux 4.4.0-109-generic
Error:
 twinkle[3253] general protection ip:7fdc4628c059 sp:7ffc3242d500 error:0 in libQt5Widgets.so.5.5.1[7fdc46131000+659000]

Repeated every ten minutes.

**Comment by fbriere** [comment]
By "repeated every ten minutes", do you mean that Twinkle _actually keeps running_, and outputs such a message every ten minutes?  (From what I understand, a GPF should imply a crash, hence my confusion.)

If it does crash, https://github.com/LubosD/twinkle/issues/114#issuecomment-364990900 applies here as well, with the addition of the `qtbase5-dbg` package.
