### ISSUE TITLE
buddylist status icons

### ISSUE THREAD

**Issue by Af0x** [LubosD/twinkle#122]
Hello,
I tried this nice SIP-communicator for the first time and I really like it so far.
I have some problems with the buddylist status symbols. It always shows the user himself as "DND". 
Also the smilies are not changing at all (within my Unix installation), e.g if you change from online to offline. You have to logout to to have a grey smilie.
Lastly I don´t know if the icon should change when a user is speaking on one line. If yes, this doesn´t work either.
Regards,
Af0x

**Comment by Af0x** [comment]
to be honest I don´t know how to find this out.

**Comment by fbriere** [comment]
As @LubosD pointed out, your SIP provider may simply not support this feature.  (Mine apparently doesn't either.)  You can confirm this for yourself by opening the log window, and seeing what happens when you try to change your availability.  For example, in my case:

```
+++ 14-8-2018 16:33:22.183159 WARNING NORMAL t_epa::recv_response
PUBLISH failure response.
501 Method Not Implemented
Event: presence, URI: sip:fbriere@sip.voicemeup.com, SIP-ETag: 
---
```

Here we can see that my SIP provider does not support the necessary `PUBLISH` method.

In such cases, it may be best to disable the "Show availability" option for each buddy, as well as the "Publish availability at startup" option in the "Presence" section of your user profile.

**Comment by fbriere** [comment]
Closing on the assumption that the SIP provider did not support Subscribe/Publish/Notify in the first place.

**Comment by evandrocoan** [comment]
My list is always show like this

![image](https://user-images.githubusercontent.com/5332158/93834396-24044980-fc52-11ea-9c7c-b6967effe304.png)

This is my sip log when I tried to change to online

![image](https://user-images.githubusercontent.com/5332158/93834457-5f067d00-fc52-11ea-96d8-af7d66c5e91b.png)

```
+++ 21-9-2020 21:30:56.380674 INFO SIP ::send_sip_udp
Send to: udp:1.0.0.1:5060
PUBLISH sip:1001@1.0.0.1 SIP/2.0
Via: SIP/2.0/UDP 10.212.134.10:5062;rport;branch=z9hG4bKzkenjtmr
Max-Forwards: 70
To: "1002" <sip:1001@1.0.0.1>
From: "1002" <sip:1001@1.0.0.1>;tag=edkiy
Call-ID: hsiolwzokwzkzfd@Pc
CSeq: 982 PUBLISH
Content-Type: application/pidf+xml
Event: presence
Expires: 3600
User-Agent: Twinkle/1.10.2
Content-Length: 192

<?xml version="1.0" encoding="UTF-8"?>
<presence xmlns="urn:ietf:params:xml:ns:pidf" entity="sip:1001@1.0.0.1"><tuple id="brpkqq"><status><basic>open</basic></status></tuple></presence>

---


+++ 21-9-2020 21:30:56.422276 INFO SIP ::process_sip_msg
Received from: udp:1.0.0.1:5060
SIP/2.0 489 Bad Event
Via: SIP/2.0/UDP 10.212.134.10:5062;branch=z9hG4bKzkenjtmr;received=10.212.134.10;rport=5062
From: "1002" <sip:1001@1.0.0.1>;tag=edkiy
To: "1002" <sip:1001@1.0.0.1>;tag=as5df99c4d
Call-ID: hsiolwzokwzkzfd@Pc
CSeq: 982 PUBLISH
Server: Asterisk PBX 13.31.0
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces, timer
Content-Length: 0


---


+++ 21-9-2020 21:30:56.423206 WARNING NORMAL t_epa::recv_response
PUBLISH failure response.
489 Bad Event
Event: presence, URI: sip:1001@1.0.0.1, SIP-ETag: 
---
```

**Comment by fbriere** [comment]
> PUBLISH failure response.
> 489 Bad Event
> Event: presence, URI: sip:1001@1.0.0.1, SIP-ETag: 

This means that while your SIP server supports (or at least recognizes) the `PUBLISH` method, it does not support the `presence` event, which pretty much amounts to the same thing as far as we are concerned.
