### ISSUE TITLE
t_gui::do_* calls GUI from non-main thread

### ISSUE THREAD

**Issue by LubosD** [LubosD/twinkle#13]
Methods such as ````t_gui::do_answer()```` make GUI calls from non-main thread and cause crashes. This currently breaks operations like ````twinkle --cmd answer````.

**Comment by LubosD** [comment]
I didn't have the strength to check that everything works, but at least it shouldn't crash.

**Comment by jodalein** [comment]
twinkle --cmd dnd
QMetaObject:: invokeMethode: No such method t_gui::do_dnd(bool,bool)

with this rework dnd from external is broken now

**Comment by LubosD** [comment]
Thank you, fixed (I hope).

**Comment by jodalein** [comment]
fixed
