### ISSUE TITLE
How do I call a SIP URI like sip:test.time@sip5060.net using Twinkle?

### ISSUE THREAD

**Issue by DAC324** [LubosD/twinkle#142]
Hello all,

as I could not find anything with regards to this question, I am asking it here. 
How can I call a SIP URI like sip:test.time@sip5060.net using Twinkle? Is that possible at all? 
Of course, I already tried entering sip:test.time@sip5060.net in the Number field for dialing but then, Twinkle gets a 408 Request Timeout error.

What do I have to do in order to get such URIs working in Twinkle?

Thank you very much for your help in advance and kind regards.

**Comment by DAC324** [comment]
Seems that I found the problem: Nowadays, there are not much test services like sip:test.time@sip5060.net available any more. Looks like there's no interest in having such services. The only working one I found was sip:thetestcall@getonsip.com or sip:thetestcall@linphone.com.

**Comment by asidt** [comment]
This seems to be the correct one: sip:thetestcall@sip.linphone.org

**Comment by fbriere** [comment]
@DAC324 and @asidt: I just wanted to thank you both!  I had unsuccessfully searched for test SIP addresses in the past (sip5060.net doesn't work for me), and now your examples have made testing code easier for me.  Thanks!
