### ISSUE TITLE
Distribute it with apt-get install twinkle-qt5

### ISSUE THREAD

**Issue by evandrocoan** [LubosD/twinkle#145]

**Comment by fbriere** [comment]
Could you explain the nature of your request a little bit further?  Twinkle (version 1.10.1 to be precise) is already present in Debian (since _stretch_) and Ubuntu (at least since _bionic_, the current LTS release).

**Comment by evandrocoan** [comment]
I thought this was another project and it was not available on the package manager. So, the version `1.10.1` is the latest version of this project?

**Comment by fbriere** [comment]
The latest version is 1.10.2, but neither Debian nor Ubuntu seem to have packaged it yet.  (I suggest you file a bug report to your distribution if you wish them to do so.)
