### ISSUE TITLE
G.729 support

### ISSUE THREAD

**Issue by LubosD** [LubosD/twinkle#15]
This library looks useful: http://www.linphone.org/technical-corner/bcg729/overview

**Comment by jodalein** [comment]
How can it test it?
I installed media-plugins/mediastreamer-bcg729-1.0.0-r1 in getnoo but i cant use -DWITH_G729=On
it says:
CMake Error at CMakeLists.txt:114 (message):
bcg729 not found!

**Comment by LubosD** [comment]
That's strange. The ebuild in question is crap (because it forces extra dependencies for an optional mediastreamer plugin), but it worked for me nonetheless.

Can you make sure that you have libbcg729.so in /usr/lib and bcg729/decoder.h in /usr/include?
