### ISSUE TITLE
Twinkle doesn't start (stack smashing detected) (Lubuntu 18.04.2)

### ISSUE THREAD

**Issue by thima2017** [LubosD/twinkle#157]
The console output:

$ twinkle
QApplication: invalid style override passed, ignoring it.
Language name: "en"
mprotect failed in ExecutableAllocator::makeExecutable: Permission denied
*** stack smashing detected ***: <unknown> terminated
Aborted (core dumped)
$
I've attached gdb.txt file. Strace output and system information are there https://bugs.launchpad.net/ubuntu/+source/twinkle/+bug/1824986
[gdb.txt](https://github.com/LubosD/twinkle/files/3394224/gdb.txt)

**Comment by fbriere** [comment]
Closing as a Qt bug.  (I have provided more details in the Launchpad bug.)
