### ISSUE TITLE
gui does not let set MAX_PTIME cutoff >50

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [LubosD/twinkle#159]
higher defined
https://github.com/LubosD/twinkle/blob/da70392f6959e16243272e8abccebd95f8bfaf47/src/audio/audio_codecs.h#L50
but limited by 
https://github.com/LubosD/twinkle/blob/da70392f6959e16243272e8abccebd95f8bfaf47/src/gui/userprofileform.ui#L826

**Comment by fbriere** [comment]
`MIN_PTIME` and `MAX_PTIME` actually apply to the setting up of the session with SDP; any offer or answer by the remote agent with a ptime outside that range will be rejected with a `488 Not Acceptable Here`.  In other words, they describe what we are able/willing to accept for this session.  (`MAX_PTIME`, in particular, determines how much memory we allocate for storing the audio samples.)

Technically, nothing prevents the GUI from imposing stricter limits if this is deemed necessary or desirable.  The current values actually date back to the very first release of Twinkle (version 0.1); your guess is as good as mine regarding the author's actual intentions at the time.  (Or lack thereof, as this might also have been a simple miscopying.)

If you believe the GUI maximum value should be raised to 80, I suggest you simply submit a PR to that effect.

(Until that PR is merged, you can always edit the configuration file manually and insert any value that you want (up to `MAX_PTIME`, obviously).  Keep in mind that your change will be overwritten if you ever edit that profile via the GUI.)

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> If you believe the GUI maximum value should be raised to 80, 
> 

I had noticed that the values do not match, whether 80 is the right choice is another question. It always depends on the codec used, maximum is up to 300 ms for others but only 150 or even 60 for e.g. speex
[minimum and maximum values that are valid per codec](https://wiki.asterisk.org/wiki/display/AST/RTP+Packetization#RTPPacketization-Codecframingoptions)

**Comment by fbriere** [comment]
This was closed by #185
