### ISSUE TITLE
Deadlocks in phone.cpp

### ISSUE THREAD

**Issue by fbriere** [LubosD/twinkle#165]
There are several places in `phone.cpp` where a deadlock can occur:

### `lines_mtx`: Read lock → Write lock (fixed in #180)

These are instances where a write lock on `lines_mtx` is requested while already holding a read lock.  The behavior of `pthread_rwlock_wrlock()` is undefined in this situation, and this will result in a deadlock on Linux.

#### Transfer with consultation without `Replaces`

This occurs when performing a consult transfer if the target does not support the `Replaces` extension.  This has already been reported in #118.

https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/phone.cpp#L342-L344
https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/phone.cpp#L370
https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/phone.cpp#L466

#### `INVITE` with `Replaces` header

This occurs on reception of an `INVITE` with a `Replaces` header.  In other words, if Twinkle is the target of a consult transfer (and the "Replaces" extension has been enabled in the config), it will deadlock once the transfer is concluded.

https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/phone.cpp#L909-L910
https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/phone.cpp#L926
https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/phone.cpp#L1277

#### `NOTIFY` received when line is idle

The exact circumstances for this are a bit complicated to me, but this can easily be triggered by starting a blind transfer, and hanging up before the other end has accepted/rejected it.

https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/phone.cpp#L1676
https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/phone.cpp#L1709
https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/phone.cpp#L1724
https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/phone.cpp#L119

#### `REFER` declined ~by the other end~

This occurs when ~a transfer is initiated and the request is refused by the other end~ the user declines an incoming call transfer request.

https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/phone.cpp#L1861
https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/phone.cpp#L1876
https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/phone.cpp#L1883
https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/phone.cpp#L140

### `lines_mtx`: Write lock → Read lock (fixed in #180)

These are instances where a read lock on `lines_mtx` is requested while already holding a write lock.  The behavior of `pthread_rwlock_rdlock()` is undefined in this situation, and this will result in `EDEADLK` being returned on Linux, which will raise an exception in `mutex.cpp`.

#### Ending a 3-way call with `hangup_both_3way` disabled (partially fixed in #166)

This occurs when hanging up a 3-way conference call if the "Hang up both lines" option is disabled.

https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/phone.cpp#L263-L264
https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/phone.cpp#L282

#### Ending a 3-way call with `hangup_both_3way` enabled

This occurs when hanging up a 3-way conference call if the "Hang up both lines" option is enabled.

https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/phone.cpp#L263-L264
https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/phone.cpp#L279
https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/phone.cpp#L89
https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/phone.cpp#L179
https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/phone.cpp#L2632

(The same path would also occur when `hangup_both_3way` is disabled, but it is currently shadowed by the previous deadlock.)

#### Other calls to `move_line_to_background()`

There are a few more places where `move_line_to_background()` (which may acquire a read lock) is called while holding a write lock, which could result in a deadlock.  These might be false positives, though, since the read lock will only be acquired if `is_3way` is true (via `cleanup_3way_state()`).

Note that most of these are currently shadowed by another deadlock that was described above.

- `move_releasing_lines_to_background()` (may be shadowed by declined REFER):
https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/phone.cpp#L140-L148

- `recvd_initial_invite()` (shadowed by INVITE+Replaces):
https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/phone.cpp#L1277-L1286

- `refer_consultation()` (shadowed by REFER w/o Replaces):
https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/phone.cpp#L466-L480

### `mutex_3way`: Recursive locking (fixed in #166)

`mutex_3way`, which is not recursive, is locked twice in the following case:

https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/phone.cpp#L153-L156
https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/phone.cpp#L162
https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/phone.cpp#L176
https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/audio/audio_session.cpp#L508
https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/audio/audio_session.cpp#L55
https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/phone.cpp#L2859-L2860

**Comment by fbriere** [comment]
For the record, while `end_call()` (which acquires a write lock) and `activate_line()` (which may acquire a read lock) sometimes call each other, this does not result in any deadlock, because:

- `activate_line()` only calls `end_call()` *before* acquiring a read lock
https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/phone.cpp#L570
https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/phone.cpp#L581
https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/phone.cpp#L596

- `end_call()` only calls `activate_line()` when `is_3way` is true, which causes the latter to return without acquiring a read lock:
https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/phone.cpp#L263-L270
https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/phone.cpp#L287
https://github.com/LubosD/twinkle/blob/05082ae12051821b1d969e6672d9e4e5afe1bc07/src/phone.cpp#L546-L555

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
might i trapped into such Deadlocks? i got twinkle processes with status "disk sleep" according to htop. but not any signal i send them, did kill them. maybe other issue. but this sounded similiar

**Comment by fbriere** [comment]
@4-FLOSS-Free-Libre-Open-Source-Software It's hard to say without more information, but do note that all the issues I mentioned involve either a call transfers or 3-way call conference.  If you didn't use either of these features, it's unlikely that you were affected by this.  (On the other hand, I don't think you can currently use these features and *not* freeze at some point.)

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
ok . no, i didnt offtopic than sorry
