### ISSUE TITLE
Handle incoming DTMF?

### ISSUE THREAD

**Issue by wurtel2** [LubosD/twinkle#167]
When making a call, I see in the ourput:

Line 1: far end supports DTMF telephone event.

However, when the far end answers the call, and presses digits, I would expect some feedback to be given by twinkle that DTMF is detected. Ideally a callback script to process these DTMF events would be ideal.

Is any handling of incoming DTMF currently possible, e.g. logging those in the log or output? To be clear, I'm talking about non-GUI operation.

**Comment by LubosD** [comment]
Personally - as I have configured such use cases - I would suggest using Asterisk, namely `features.conf`. It may look like a giant beast, but setting up stuff like this is quite easy... Twinkle isn't really the right tool for this, I'd say.

features.conf:
```
[applicationmap]
myexample => #,peer,System(/etc/asterisk/scripts/myscript.sh)
```

And then in extensions.conf, you just call `Set(__DYNAMIC_FEATURES=myexample)`. The script will be run when # is pressed.

**Comment by wurtel2** [comment]
I've always been a bit overwhelmed by asterisk, but I'll give it a try. Thanks for the feedback!

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
yes, inbound dtmf is logged into stdout.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> However, when the far end answers the call, and presses digits, I would expect some feedback to be given by twinkle that DTMF is detected.
> 

![image](https://user-images.githubusercontent.com/46166740/69463412-cf671800-0d7b-11ea-9eea-e457d0b50431.png)

> Is any handling of incoming DTMF currently possible, e.g. logging those in the log or output? To be clear, I'm talking about non-GUI operation.

@wurtel2 don't you see how it is handled already in non-gui ?
``
```
$ twinkle-console 
Twinkle 1.10.2, February 14, 2018
Copyright (C) 2005-2015  Michel de Boer and contributors

Users:
* test
     <sip:test@localhost>

Local IP:       255.255.255.255


test: registering phone...

Twinkle> 
test: registration succeeded (expires = 300 seconds)


Line 1: incoming call
From:           Test <sip:**666@localhost>
To:             sip:test@127.0.0.1:5060

Twinkle> answer
warning: Unknown speex_preprocess_ctl request:  2
warning: Unknown speex_preprocess_ctl request:  6
warning: Unknown speex_preprocess_ctl request:  30
warning: The VAD has been replaced by a hack pending a complete rewrite

Line 1: far end supports DTMF telephone event.

Twinkle> 
Line 1: call established.


Line 1: DTMF detected: 1


Line 1: DTMF detected: 2


Line 1: DTMF detected: 3


Line 1: DTMF detected: A


Line 1: DTMF detected: B


Line 1: DTMF detected: C


```
in gui just parse for Signal code in the log with sip log enabled

sip log:

```
``

Content-Type: application/dtmf-relay
Content-Length:    24

Signal=1
Duration=100

...

Content-Type: application/dtmf-relay
Content-Length:    24

Signal=2
Duration=100

...


Content-Length:    24

Signal=3
Duration=100
```

**Comment by fbriere** [comment]
> in gui just parse for Signal code in the log with sip log enabled
> 
> sip log:
> 
> ```
> Content-Type: application/dtmf-relay
> Content-Length:    24
> 
> Signal=1
> Duration=100
> ```

Note that this is only the case for DTMF sent via SIP INFO (RFC 2976/6086).  DTMF sent as RTP payload (RFC 2833/4733) will trigger shorter, standard (non-SIP) messages:

```
+++ 8-12-2019 11:35:55.871986 INFO NORMAL t_audio_tx::run
Audio tx line 1: detected DTMF event - 5
---
```

**Comment by fbriere** [comment]
While calling a script on each DTMF event might not be too difficult in itself (I'm guessing), that script would ignore everything about the context of the current phone call (including which digits have been pressed beforehand), which could render such a feature rather useless for some people.

Calling a single script during the whole call (with all the necessary meta-information regarding said call) and feeding it events on standard input would probably be more useful.  And much more complex to implement, as I don't think the scripts infrastructure was designed to support this in the first place.  (Though, again, I might be wrong about this.)

I will therefore defer to @LubosD's judgement, namely that this is a feature best left to an intermediary (such as Asterisk), and close this issue accordingly.
