### ISSUE TITLE
no sound with Twinkle

### ISSUE THREAD

**Issue by ovitus** [LubosD/twinkle#172]
I have Twinkle configured with our Asterisks VOIP server, and can make calls, but I get no sound. I've tried various settings in Twinkle with ALSA and I've tried disabling Pulseaudio completely. I'm on Fedora release 29 and using XFCE. Any ideas as to what the issue may be?

**Comment by fbriere** [comment]
First question: is ALSA working properly in your case?

Take a look at Twinkle's log, look for the "Opening ALSA device:" lines corresponding to when the call was established (typically between the `SIP/2.0 200 OK` and "starting RTP session." entries), note the name of the device opened for playing, and run `aplay -D DEVICENAME /usr/share/twinkle/ringtone.wav` (or any other WAV file).  Can you hear the file correctly in your headset?

**Comment by clarified** [comment]
Twinkle in debian testing seems t have problems with accessing the ALSA sound devices:
Critical: Cannot open ALSA driver for PCM playback: Device or resource busy

Sun 21:07:45
Critical: Cannot open ALSA driver for PCM playback: Device or resource busy

Sun 21:07:45
Critical: Cannot open ALSA driver for PCM playback: Device or resource busy

Linphone and other applications do not have this problem. And no, linphone was not running at the same time.

I am very rusty on ALSA so I have done no diagnosis as yet.

**Comment by clarified** [comment]
It is not just Debian.

Compiling the lastest git version gives the same problem:

+++ 7-1-2021 16:19:07.919267 INFO NORMAL t_alsa_io::open
Opening ALSA device: plughw:0,
play
---

+++ 7-1-2021 16:19:07.919335 CRITICAL NORMAL t_alsa_io::open
snd_pcm_open failed: Device or resource busy

Trying with aplay gives a similar problem:
$ aplay -D plughw:0,0
aplay: main:830: audio open error: Device or resource busy
 
but aplay works normally. I need to refresh my minimal knowledge of ALSA...

**Comment by fbriere** [comment]
For the record, @clarified provided more information about their own situation in [Debian bug #979180](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=979180), which I have just closed with an explanation.

With that settled, and given the lack of feedback from @ovitus, I am now closing this issue.
