### ISSUE TITLE
false sdp answer to sdp offer including fax vbd=yes attribute

### ISSUE THREAD

**Issue by rolstein62** [LubosD/twinkle#184]
when twinkle receives an Invite with SDP offer that includes dynamic codec g711a with vbd=yes in addition to the normal G711a codec, then its answer includes the wrong sdp response.
Instead of answering with 8 G711a it responds with the dynamic codec (121 in this case) which it is not capable of. For that reason the audio connection fails.
[twinkle false sdp answer.pcapng.zip](https://github.com/LubosD/twinkle/files/4091095/twinkle.false.sdp.answer.pcapng.zip)

**Comment by fbriere** [comment]
Thank you very much for your detailed analysis, as well as the packet capture.  These helped a **lot**.  :heart:

Now, from what (little) I understand, I'm not sure that Twinkle is in the wrong here.  After all, payload type numbers are not required to be identical between the offer and answer (RFC 3264 makes this a "SHOULD", not a "MUST").  In your example, payload type 121 in the answer is simply marked as `PCMA/8000` and should be treated as such.  Failure to do so would seem to be a bug from the remote SIP client.  (Unless I'm mistaken, which is not unlikely.)

Nevertheless, Twinkle should indeed be nice and use the first payload type number that was listed.  I have just submitted #201 to fix this; could you give it a try and confirm that it does the job?
