### ISSUE TITLE
Start a call from command line

### ISSUE THREAD

**Issue by mooooonbaby** [LubosD/twinkle#197]
Twinkle works with the GUI, but not using the cli. When i try

`twinkle call <number>`

it opens the GUI and i habe to select a the profile. After that nothing happens. The call isnt started. 

What i want is to Start a call in a Maschine without a desktop and run it completely from Commando line.

**Comment by fbriere** [comment]
The correct syntax is `twinkle --call <number>`.  This requires that an instance of Twinkle is already running, either in GUI mode or CLI mode (`-c`).  The command will signal the running instance to place the call and will return immediately.

(Note that this will *not* work with `twinkle-console`.)
