### ISSUE TITLE
Manual  link in Help menu opens "Penis Extension" site

### ISSUE THREAD

**Issue by CarlFink** [LubosD/twinkle#200]
Apparently Twinklephone.com has been taken over by "Review of the 8 Best Penis Extenders of 2019" (That's the page title and H1 text.) I'm using 1.1, the version in the current Debian, so perhaps this was fixed in later Twinkle releases? I don't feel like installing the latest just to check--on my production systems, I try to to stick to the package manager.

**Comment by LubosD** [comment]
Yes, this has been fixed already.
