### ISSUE TITLE
Twinkle failed to create socket

### ISSUE THREAD

**Issue by shegs01** [LubosD/twinkle#210]
Hi,

I recently installed twinkle from source and I could not use twinkle with [Opensips](https://www.opensips.org/) as both are listening on the same SIP port 5060. 

Basically, if Opensips is running, I can't use twinkle and vice versa. I am aware that 2 apps can't listen to the same port at the same time, so how do I recify this from twinkle. I am new to socket programming and this is a bit challenging for me. Also, why is twinkle creating UDP and TCP sockets while other SIP clients don't?

Thanks in advance for your help.

**Comment by fbriere** [comment]
The SIP port number can be changed under _Edit/System settings/Network/SIP port_.  If the socket is already taken (and Twinkle cannot be started in the first place), a `--sip-port` command-line option was added in #158 (only in the main branch).

As for UDP vs. TCP, either can be used for SIP, and Twinkle supports both.
