### ISSUE TITLE
Sorting of the call list seems to be incorrect

### ISSUE THREAD

**Issue by urbanware-org** [LubosD/twinkle#211]
I'm using Twinkle 1.10.2 and there seems to be a bug with the order of the calls inside the call list (where I can see the incoming and outgoing calls). It occurs every time I (re-)open the window containing the list.

By default, the sorting is ascending (the oldest call is on top of the list). However the "arrow" on the time column points up, which actually means that the list should be sorted descending (with the latest call is on top), but it's not:

![twinkle_call_list](https://user-images.githubusercontent.com/19925115/89317147-48de3680-d67d-11ea-806c-6cb0282d6b8c.png)

When I click on the column header, the "arrow" turns down and the list order does not change (which is correct as the list still is ascending).

Then, I click on the column header once again, so the "arrow" turns up and the sorting is correct (latest calls are on top of the list).

I hope I was able to explain this in a way that was understandable.

Thanks in advance!

**Comment by fbriere** [comment]
This is due to a [Qt bug](https://bugreports.qt.io/browse/QTBUG-86268) introduced in 5.13, which breaks the initial sorting, as well as any re-sorting after inserting/editing a row, of both the call history and address book lists.

**Comment by urbanware-org** [comment]
I see. Thank you for the information.

If I get that right, the bug in Twinkle will be gone as soon as the Qt team fixed it and deployed a new version?

**Comment by fbriere** [comment]
> If I get that right, the bug in Twinkle will be gone as soon as the Qt team fixed it and deployed a new version?

Correct.  This is a runtime issue, so it merely depends on which version of the Qt library is loaded when Twinkle is launched, and not which version it was compiled with.  (A fix has already been authored upstream, but I don't know if it will make it in time for 5.15.1.)

That said, I can easily work around this bug, which is what I was planning to do, after confirming that it was indeed a Qt bug (and not a mistake on our part).  Hence why I haven't closed this issue yet.

**Comment by urbanware-org** [comment]
I have seen that the [Qt bug](https://bugreports.qt.io/browse/QTBUG-86268) has officially been fixed which also solves this issue (as the sorting bug in Twinkle is gone with Qt 5.15.2).
