### ISSUE TITLE
Make "Main Toolbar" option also available under "View" menu

### ISSUE THREAD

**Issue by evandrocoan** [LubosD/twinkle#220]
Today, out of nowwhere, my menu buttons are missing:

![image](https://user-images.githubusercontent.com/5332158/101956779-ee328980-3bde-11eb-80f0-3839c8e1e537.png)

How go get them back?

![image](https://user-images.githubusercontent.com/5332158/101956696-cf33f780-3bde-11eb-9f36-66828490d650.png)

Related to: https://github.com/LubosD/twinkle/issues/10 - OSD with mute & hangup buttons

**Comment by evandrocoan** [comment]
I just deleted the file `/home/evandro_coan/.twinkle/gui_state.ini` after closing twinkle and the problem was fixed and I opened it again.

**Comment by fbriere** [comment]
> How go get them back?

If you right-click on the menu bar or toolbar, you will see a "Main Toolbar" option, allowing you to toggle its display.  I guess you accidentally unselected it without noticing.

To be honest, I wasn't aware of this option myself, and it's not obvious how to toggle it back.  One would expect to find it under the "View" menu; I'll try to add it there later on.
