### ISSUE TITLE
bug: codec order G722

### ISSUE THREAD

**Issue by userofryzen** [LubosD/twinkle#226]
I have uncheck "follow codec preference from far end ", two options. And I have put:
![imagen](https://user-images.githubusercontent.com/33232977/115171674-d8206280-a0c3-11eb-88ef-e3b90afb988d.png)
But when I'm gonna call the codec it uses is G729.
If I put G711A second and first G722 then the program uses G711A.

But if I disable G711 and G729, then, there is possibilites to call with G722 codec. So, in my opinion, it should be a problem with order preference for G722 codec because the order is not follow. 
If I put G722, G729 and G711 the program calls wih G729, If I put G722,G711 and G729 then the program calls with G711. So the program follows the order but not in all the codecs.

Steps to reproduce:
Uncheck both options of follow codec preference from far end( this way there is no more variables here).
Put G722 first and add whatever supported codec like G711 or G729  probably. You'll see that the program are going to call with G711 or G729, depends on whatever have you put first directly, but if you delete all codecs from active list, then, you can call with G722 codec finally.

**Comment by userofryzen** [comment]
To sum up: the prrogram fails to follow the codec preference with G722 codec at least. G729 and G711 are correct with the order but when I add G722 the program skip that codec and fall on another one. 
When I put G722 alone in acive list and no others supported ones, the call goes with G722 codec without problems.

**Comment by fbriere** [comment]
Glad to hear you found the answer to this puzzle!
