### ISSUE TITLE
SMALL TWINKLE ISSUE:

### ISSUE THREAD

**Issue by MENTD** [LubosD/twinkle#230]
Greetings!  This is not a joke! (But it's a pretty funny issue!)
In TWINKLE, when going to HELP and selecting MANUAL, you are taken to a PENIS ENHANCEMENT SITE.

Cheers! 8)

**Comment by mkubecek** [comment]
The help linked to to old Twinkle web page current maintainers have no control over. Apparently the old domain expired and was registered by spammers/squatters. The link has been fixed in git by commits 05082ae12051 and b756c8cdebc4
