### ISSUE TITLE
Could NOT find libmagic on Centos 8 Stream

### ISSUE THREAD

**Issue by doczkal** [LubosD/twinkle#232]
while running cmake I get the following output

> $ cmake .. -DWITH_ALSA=OFF -DWITH_SPEEX=ON -DWITH_ILBC=ON -DWITH_ZRTP=ON -DWITH_G729=ON -DWITH_QT5=OFF
> -- The C compiler identification is GNU 8.5.0
> -- The CXX compiler identification is GNU 8.5.0
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: /usr/bin/cc - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: /usr/bin/c++ - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found LibXml2: /usr/lib64/libxml2.so (found version "2.9.7") 
> -- libmagic version: 5.33
> CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
>   Could NOT find LibMagic (missing: LibMagic_LIBRARY LibMagic_INCLUDE_DIR)
> Call Stack (most recent call first):
>   /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
>   cmake/FindLibMagic.cmake:61 (find_package_handle_standard_args)
>   CMakeLists.txt:24 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/$USER/git/twinkle/twinkle-1.10.2/build/CMakeFiles/CMakeOutput.log".

Any idea where to look at? 

I have installed what I think is the right package.

> $ yum info file-libs.*
> Last metadata expiration check: 2:42:05 ago on Fri 18 Jun 2021 04:07:50 PM CEST.
> Installed Packages
> Name         : file-libs
> Version      : 5.33
> Release      : 20.el8
> Architecture : i686
> Size         : 6.1 M
> Source       : file-5.33-20.el8.src.rpm
> Repository   : @System
> From repo    : baseos
> Summary      : Libraries for applications using libmagic
> URL          : http://www.darwinsys.com/file/
> License      : BSD
> Description  : 
>              : Libraries for applications using libmagic.
> 
> Name         : file-libs
> Version      : 5.33
> Release      : 20.el8
> Architecture : x86_64
> Size         : 6.1 M
> Source       : file-5.33-20.el8.src.rpm
> Repository   : @System
> From repo    : baseos
> Summary      : Libraries for applications using libmagic
> URL          : http://www.darwinsys.com/file/
> License      : BSD
> Description  : 
>              : Libraries for applications using libmagic.

**Comment by p5panam** [comment]
have you successfully installed it on centos8 ?

**Comment by doczkal** [comment]
@p5panam no, I had no luck yet. Not sure what packages are missing.

**Comment by fbriere** [comment]
> > Name         : file-libs
> > Summary      : Libraries for applications using libmagic

You need not only the library, but its development files as well.  According to Google, that should be `file-devel`.
