### ISSUE TITLE
Not able to create UDP socket (SIP), error 98

### ISSUE THREAD

**Issue by uwedisch** [LubosD/twinkle#238]
Hello,

with my system configuration Twinkle is not able to create an UDP socket. There is error 98 given. The message is:

Fehler beim Anlegen: UDP socket (SIP) auf port 5060
strerror_r is not available: 98

![grafik](https://user-images.githubusercontent.com/24267159/139736577-d61669b1-d2d5-4114-806b-5554ff902f78.png)

My system has these interfaces:

br0
br0.1
enp5s0
lo
virbr0
vnet0
vnet1
vnet2

Because of virtualization and VLANs on br0 and br0.1 the physical interface enp5s0 has no IP address.

Which interface should be used from Twinkle?
Is there any config parameter to choose the right interface (br0 in my case)?

**Comment by GauravRteli** [comment]
Even i am getting this kind of issue have you solved this issue ?

**Comment by uwedisch** [comment]
Yes, it's solved and Twinkle working since them.
I searched my notes, but found nothin what I was doing to solve this issue.

**Comment by DimonLimonPerdafon** [comment]
vim ~/.twinkle/twinkle.sys

Замемни SIP порт (sip_port=5060) на любой другой свободный порт.

Перезапусти Twinkle.
