### ISSUE TITLE
no-manual-page

### ISSUE THREAD

**Issue by glixx** [LubosD/twinkle#24]
twinkle.i586: W: no-manual-page-for-binary twinkle-console
twinkle.i586: W: no-manual-page-for-binary twinkle

**Comment by glixx** [comment]
Man page for twinkle is present here: http://ftp.br.debian.org/debian/pool/main/t/twinkle/twinkle_1.4.2-4.debian.tar.xz

**Comment by LubosD** [comment]
There is still no man page for twinkle-console though, but this binary has no options...
