### ISSUE TITLE
ALSA doesn't work

### ISSUE THREAD

**Issue by plomari** [LubosD/twinkle#244]
>Cannot access the speaker (ALSA: default).
>Cannot access the microphone (ALSA: default).

With default configuration. No other programs have audio problems. Built from git master (9e3dadb4b1a338). Pretty simple report, but not sure what else to say.

**Comment by fbriere** [comment]
> Pretty simple report, but not sure what else to say.

I can probably think of a few things.  :smirk:

- Are you using either PulseAudio or PipeWire?  (Unlike most applications, Twinkle still doesn't use those and accesses ALSA directly, so other programs working fine doesn't mean that Twinkle will too.)
- What error message do you see in the log?  (Available either under the "View/Low" menu entry, or in `~/.twinkle/twinkle.log`.)  Look for anything right after `Opening ALSA device:`.
- Can you successfully run `speaker-test` (typically found in the `alsa-utils` package)?  If you get an error message, it's unlikely that Twinkle will fare much better.

**Comment by plomari** [comment]
> Are you using either PulseAudio or PipeWire? (Unlike most applications, Twinkle still doesn't use those and accesses ALSA directly, so other programs working fine doesn't mean that Twinkle will too.)

No. My audio setup is native ALSA. PulseAudio and PipeWire are both not installed.

> What error message do you see in the log? (Available either under the "View/Low" menu entry, or in ~/.twinkle/twinkle.log.) Look for anything right after Opening ALSA device:.

From twinkle.log:
```+++ 6-2-2022 16:59:41.645547 INFO NORMAL t_alsa_io::open
Opening ALSA device: default
play
capture
---

+++ 6-2-2022 16:59:41.645607 INFO NORMAL t_alsa_io::open
Opening ALSA device: default
play
---

+++ 6-2-2022 16:59:41.646587 INFO NORMAL t_alsa_io::open
Opening ALSA device: default
capture
---
+++ 6-2-2022 16:59:41.646741 CRITICAL NORMAL t_alsa_io::open
snd_pcm_open failed: Invalid argument
---

+++ 6-2-2022 16:59:41.646781 CRITICAL NORMAL t_audio_io::open
Open audio device failed
---

+++ 6-2-2022 16:59:41.646885 INFO NORMAL t_alsa_io::open
Opening ALSA device: default
play
capture
---

+++ 6-2-2022 16:59:41.646905 INFO NORMAL t_alsa_io::open
Opening ALSA device: default
play
---
+++ 6-2-2022 16:59:41.647760 INFO NORMAL t_alsa_io::open
Opening ALSA device: default
capture
---

+++ 6-2-2022 16:59:41.647910 CRITICAL NORMAL t_alsa_io::open
snd_pcm_open failed: Invalid argument
---

+++ 6-2-2022 16:59:41.647947 CRITICAL NORMAL t_audio_io::open
Open audio device failed
---
```
> Can you successfully run speaker-test (typically found in the alsa-utils package)? If you get an error message, it's unlikely that Twinkle will fare much better.

Yes. Other audio applications work too.

**Comment by fbriere** [comment]
> ```
> +++ 6-2-2022 16:59:41.646587 INFO NORMAL t_alsa_io::open
> Opening ALSA device: default
> capture
> ---
> +++ 6-2-2022 16:59:41.646741 CRITICAL NORMAL t_alsa_io::open
> snd_pcm_open failed: Invalid argument
> ---
> ```

Ah, so it's the audio *input* that's failing.  Is you default audio device capable of recording?  Does `arecord -f U8 >/dev/null` run correctly?

**Comment by plomari** [comment]
```
$ arecord -f U8 >/dev/null
ALSA lib pcm_dmix.c:1005:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
arecord: main:831: audio open error: Invalid argument
```
No. Though I've tried other devices before.

**Comment by fbriere** [comment]
> ```
> ALSA lib pcm_dmix.c:1005:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
> ```

Well, that settles that.

> No. Though I've tried other devices before.

And what did the log say when using *those* devices?  Did `aplay`/`arecord` work for them (using the `-D` option)?
