### ISSUE TITLE
`1.10.3` point release including new manual URL

### ISSUE THREAD

**Issue by fbriere** [LubosD/twinkle#257]
@LubosD  Would you object to a `1.10.3` point release including only the new manual URL (#240) and nothing else?  This matter has (understandably) generated a lot of reactions, and while the fix is a simple one-liner, it's more likely to be adopted by most distros if we put an actual version number to it.

(My next proposal will be a `1.10.x` branch where we can cherry-pick other simple fixes from `master`, but let's start with this one step.)

If you'd like, I'll be glad to take care of all the work.  You just need to give me the OK sign.  :smile:

**Comment by LubosD** [comment]
Sure, let's do it!

**Comment by fbriere** [comment]
Done!

I also took the opportunity to create a `twinkle-1.10.x` branch; there are quite a few more patches worthy of sending downstream.  I'm not quite sure what workflow would be best for this; for now, I think I'll submit one big PR against that branch once I'm done cherry-picking.  Let me know if you have a different opinion.

(Now I'll go over and put up a note in #206, to let everyone know they shouldn't celebrate too soon.  :grin:)
