### ISSUE TITLE
Modal windows positioning on multi-monitor setup

### ISSUE THREAD

**Issue by dreua** [LubosD/twinkle#271]
On my multi-monitor setup each new window (e.g. information to create a profile and subsequent dialog windows) are placed in the top left corner on the leftmost monitor. These windows are easily overlooked and it's annoying to use the wizard if each window is created on the farthest corner.

**Comment by fbriere** [comment]
I'm pretty sure this is an issue with either Qt (such as [this example](https://linuxreviews.org/The_Qt_5.15_Disaster_On_Multi-Monitor_Setups)) or your window manager, as Twinkle does not know (or care) about the number or monitors being used.

Which window manager (or desktop environment) are you running?  And do you see a similar behavior with other Qt applications?

**Comment by dreua** [comment]
I'm using Gnome + X11, OS is Fedora 35. I always need to switch to X11 because Wayland doesn't work for me, the rest should be defaults of Fedora Linux.

**Comment by dreua** [comment]
I'll need to check other qt applications, most stuff I use is Gtk

**Comment by dreua** [comment]
Tbh I'm not using twinkle an more therefore I'll just close this issue.
