### ISSUE TITLE
Hangs on ending call

### ISSUE THREAD

**Issue by mantinan** [LubosD/twinkle#274]
Hi!

I'm using Debian version of twinkle 1.10.2 on Debian Bullseye, I have been expiriencing problems after a call is ended, the interface is hanged. I thougt it was a problem with the graphical interface, but today I compiled 1.10.3 and saw that it is happening also on text mode, the session was like this:

$ twinkle -c

Firewall/NAT discovery in progress.
Please wait.

Twinkle 1.10.3, February 18, 2022
Copyright (C) 2005-2015  Michel de Boer and contributors

Users:
* 99999
    99999 <sip:99999@XX.XX.XX.XX:5060>

Local IP:       255.255.255.255

99999: registering phone...

Twinkle> 
99999: registration succeeded (expires = 600 seconds)
Registrar Date: Mon, 09 May 2022 11:40:53 GMT

Twinkle> call 88888
Twinkle> 
Line 1: received 100 Trying

warning: The VAD has been replaced by a hack pending a complete rewrite

Line 1: far end supports DTMF telephone event.

Line 1: received 183 Session Progress

Twinkle> 
Line 1: received 180 Ringing

bye

Line 1: call ended.

Twinkle remays there, prompt doesn't come back and doesn't end.

I don't know if I can activate debugging or similar to provide more info on the problem, if so, just let me know what to do.

Regards.

**Comment by fbriere** [comment]
> I compiled 1.10.3

1.10.3 was only a minor release that simply fixed the URL for the manual.  Could you try again with the `master` branch?  There are quite a few fixes in there that have yet to be released.

> I thougt it was a problem with the graphical interface, but today I compiled 1.10.3 and saw that it is happening also on text mode,

That was smart of you to successfully remove the GUI from the equation.  Thanks!

> I don't know if I can activate debugging or similar to provide more info on the problem, if so, just let me know what to do.

You can enable debug messages under _Edit_ > _System settings_ > _Log_ > _Log debug reports_.  The log itself is located in `~/.twinkle/twinkle.log`.  (It's also available under _View_ > _Log_, but that obviously won't help you if the interface is frozen.)

The end of a call looks something like this for me (with most lines omitted):

```
+++ 12-5-2022 01:22:03.117411 INFO SIP ::send_sip_udp
Send to: udp:72.55.158.193:5060
BYE sip:*98@72.55.158.193:5060;transport=udp SIP/2.0

+++ 12-5-2022 01:22:03.147603 INFO NORMAL t_audio_session::~t_audio_session
Line 1: stopping RTP session.
---

+++ 12-5-2022 01:22:03.150879 INFO NORMAL t_audio_session::~t_audio_session
Line 1: RTP session stopped.
---

+++ 12-5-2022 01:22:03.150917 DEBUG NORMAL t_alsa_io::~t_alsa_io
snd_pcm_close, handle = 0x7f800c00b490
---

+++ 12-5-2022 01:22:03.163339 DEBUG NORMAL t_alsa_io::~t_alsa_io
snd_pcm_close, handle = 0x7f800c031ce0
---

+++ 12-5-2022 01:22:03.175281 DEBUG NORMAL t_phone::move_line_to_background
Moved line 1 to background position 4
---

+++ 12-5-2022 01:22:03.189421 INFO SIP ::process_sip_msg
Received from: udp:72.55.158.193:5060
SIP/2.0 200 OK

+++ 12-5-2022 01:22:03.189571 DEBUG NORMAL t_abstract_dialog::~t_abstract_dialog
Destroy dialog, id=13090
---

+++ 12-5-2022 01:22:03.189617 DEBUG NORMAL t_abstract_dialog::~t_abstract_dialog
Destroy dialog, id=13083
---

+++ 12-5-2022 01:22:03.190130 DEBUG NORMAL t_phone::cleanup_dead_lines
Removed dead line 4
---
```

Given how you actually got the `Line 1: call ended.` message, I suspect that Twinkle is only freezing *after* all of the above.  In that case, the next thing to try afterwards would be to place an *incoming* call from outside, and see if anything appears in the log.  (This could help determine whether it's Twinkle as a whole that's frozen or only its interface.)

**Comment by mantinan** [comment]
Testing withtout the GUI was because I was thinking it was the UI the one that was broken.

I have tested master and works like a charm both in command line and on the GUI.

Thanks!
