### ISSUE TITLE
Twinkle, Where to specify Server's SIP port ?

### ISSUE THREAD

**Issue by fikoulli** [LubosD/twinkle#286]
Hi,

Please,
Where can I specify the SIP port of the server ?
I tested by putting in domain : 192.168.10.1:5038
but its not working

Thanks

**Comment by fbriere** [comment]
> Please, Where can I specify the SIP port of the server ? I tested by putting in domain : 192.168.10.1:5038 but its not working

This is the right syntax, but the wrong location.

The domain, found in the [user section](https://mfnboer.home.xs4all.nl/twinkle/manual.html#profile_user), is the domain part of your SIP address; it identifies who you *are*.  (And as @Cyborgscode noted, when connecting to a SIP server, you most probably need to use an actual domain name, not an IP address.)

The settings related to the SIP server are, fittingly enough, located in the [SIP server section](https://mfnboer.home.xs4all.nl/twinkle/manual.html#profile_sip_server); they specify where Twinkle should connect *to*.  You should therefore add `:5038` to the "Outbound proxy" value.  (In most cases, you can leave the "Registrar" field blank, and Twinkle will reuse the same value for both.)
