### ISSUE TITLE
Always Ask for Credentials when Startup

### ISSUE THREAD

**Issue by rafaelkoslop** [LubosD/twinkle#291]
I have installed Twinkle by Ubuntu Store, version (1.10.2+dfsg). It works fine, but it ask for credencials everytime I start it.

**Comment by fbriere** [comment]
You need to provide correct values in the "Authentication name" and "Password" fields (and "Realm", if non-empty) of the [User section](https://mfnboer.home.xs4all.nl/twinkle/manual.html#profile_user) of your [user profile](https://mfnboer.home.xs4all.nl/twinkle/manual.html#profile_editor).

Quoting from the manual:
> If Twinkle needs to authenticate (eg. for a registration) and the realm, name or password are wrong, then you will be interactively asked for your correct credentials during the authentication process. These credentials will then be cached till you exit Twinkle. They will not be written to your profile.
