### ISSUE TITLE
PulseAudio and/or Pipewire devices missing

### ISSUE THREAD

**Issue by urbanware-org** [LubosD/twinkle#293]
I have the following environment:

* Fedora 35
* Kernel 5.18.16-100
* Pipewire 0.3.56-1
* Twinkle 1.10.3

Inside the Twinkle audio settings, I can only select ALSA devices in the list of sound cards for the devices I need.

Other programs (e.g. VLC, Audacity and browsers) seem to at least use PulseAudio. I took a look into the audio settings of those programs. Inside the VLC settings I can see that PulseAudio is set as output module and inside Audacity I can either use "default" or explicitly "pipewire", which both work. I guess PulseAudio is the default audio module so I can imagine the browsers also use it then.
 
Anyway, I can for instance listen to music in all of them simultaneously without any problems. No one comes in between of another.
 
When I then start Twinkle (or if it is already running and I try to make or receive a call), it tells me that the audio devices cannot be accessed, due to the selected ALSA devices. Twinkle itself works as expected as long as no other program uses the audio device in any way.
 
The other way around, when I'm on a call and then start music, I don't hear it unless I hang up inside Twinkle. So, in such case Twinkle has the "right of way" and blocks the audio output of other programs (inside the media player I can see that the music is running, but I don't hear it). As soon as I hang up in Twinkle I can instantly hear the music playing.

In issue #161 users tell that their Twinkle works with Pipewire, also with [Fedora 35 and Twinkle 1.10.3](161#issuecomment-1143545411).

Am I missing something?

Below is the screenshot from the audio device list from Twinkle. Both USB devices are only available with ALSA:

![twinkle_pipewire_missing](https://user-images.githubusercontent.com/19925115/183623575-ab8b1a57-787f-4fa9-8b63-781dae9c678f.png)

**Comment by fbriere** [comment]
> Am I missing something?

Probably the [`pipewire-alsa` package](https://packages.fedoraproject.org/pkgs/pipewire/pipewire-alsa/).  :grin:

(From what I understand, the PipeWire plugin included in that package will provide additional "fake" ALSA devices that you can then use in Twinkle.)

**Comment by fbriere** [comment]
My bad.  I failed to realize that Twinkle only lists ALSA devices from actual sound cards.  You need to select "ALSA: other device", and specify the name of the device you want to use (most probably `pipewire` in your case; you can confirm with `aplay -L`).

**Comment by urbanware-org** [comment]
No problem. :slightly_smiling_face: 

I'm back in the office again on Tuesday and can try it out then.

**Comment by urbanware-org** [comment]
I have set the audio devices as you suggested:

![pipewire_success](https://user-images.githubusercontent.com/19925115/184940367-f2cb4e87-ab14-46af-9266-b8993f7a0b0b.png)

Works fine! :grinning:  

Thanks a lot!
