### ISSUE TITLE
User profiles can't be disabled

### ISSUE THREAD

**Issue by ppetr** [LubosD/twinkle#30]
I have multiple user profiles and I want to keep some of them disabled (they're just for testing etc.). But If I go to _Edit > System settings_ and disable some of them in the _General_ tab, group _Startup_, the selection isn't registered, they're still all considered enabled. Other settings get saved properly.

This applies to Twinkle 1.9.0 - 10 July 2015

(Unrelated: thanks for reviving Twinkle!)

**Comment by aixtemaadmins** [comment]
I cant reproduce it, i also have 3 profiles at my PC and i can select and deselect them.
If i start one only this is enabled. 
Can u call all Profiles?

**Comment by ppetr** [comment]
Actually, I have just one working profile. The other ones are currently non-working, the servers aren't currently available.

**Comment by LubosD** [comment]
I can confirm there's something fishy. I could check more profiles (and they would remain checked), but unchecking doesn't work.

**Comment by ppetr** [comment]
Thank you!
