### ISSUE TITLE
How to change GUI language?

### ISSUE THREAD

**Issue by wonder75** [LubosD/twinkle#303]
Hi, sorry for asking such a basic question but i checked all the settings, the manual and ./twinkle --help, but couldn't find a way to change the GUI language. Where would I set it? Thanks a lot!

**Comment by LubosD** [comment]
In pretty much all apps on Linux, this is a system-wide or per-user setting, not an application option.

Perhaps you should be able to change the language by running the app with  the LANG env var set to a different value.
