### ISSUE TITLE
Number conversion

### ISSUE THREAD

**Issue by vktRus** [LubosD/twinkle#320]
How to number convert from "+7*" to "8*"?
<a href="https://ibb.co/1fWmby3"><img src="https://i.ibb.co/1fWmby3/2023-07-07-11-10-44.png" alt="2023-07-07-11-10-44" border="0"></a>

**Comment by fbriere** [comment]
Replacing any `+7*` prefix with `8*` can be achieved with the match expression `\+7\*([0-9]*)` and the replacement string `8*$1`.  (You can see [some more examples](https://mfnboer.home.xs4all.nl/twinkle/manual.html#profile_address_format) in the online manual.)
