### ISSUE TITLE
BLF

### ISSUE THREAD

**Issue by sinyb** [LubosD/twinkle#33]
First I would like to thank you for reviving Twinkle, it used to be my favorite SIP client on Linux, but it was very hard to impossible to install/configure it on newer distributions.

I have a suggestion: it would be nice if "buddies" would act as real BLF buttons, since they are already using SIP subscriptions and probably get necessary information from Asterisk, so they change icon when buddy is ringing/busy/in dnd state/etc, as can be found in https ://wiki.asterisk.org/wiki/display/AST/Device+State, and not only online/offline as it seems to be doing now.

Best regards and keep up the good work,
Siniša Bandin

**Comment by LubosD** [comment]
Duplicates #11.
