### ISSUE TITLE
Enable continuous integration testing

### ISSUE THREAD

**Issue by petercolberg** [LubosD/twinkle#41]
Given that #40 was merged despite failing to compile, what do you think of configuring a Travis instance for twinkle to perform automatic build testing? If yes, please see the instructions on [how to enable Travis](https://docs.travis-ci.com/user/getting-started/) for the twinkle repository.

I can help preparing a `.travis.yml` file.

**Comment by LubosD** [comment]
I have TeamCity running at http://teamcity.dolezel.info with plenty of RAM and CPU power. I'll set up a new Docker agent...

**Comment by petercolberg** [comment]
I generally favour self-hosted infrastructure for free software projects. However this would put the burden of keeping the instance running and up to date on you instead of the Travis CI maintainers. Could you enable the Travis support and give it a try?

**Comment by LubosD** [comment]
OK, enabled. If you can create .travis.yml, it would be very helpful, I've never written one before.
