### ISSUE TITLE
Please port away from Qt Quick 1

### ISSUE THREAD

**Issue by mitya57** [LubosD/twinkle#52]
QtQuick1 (which provides QDeclarative* classes) is deprecated upstream and is not part of Qt 5.6 release.

Please port this module to Qt Quick 2 if you want it to work with Qt 5.6. See [this page](http://doc.qt.io/qt-5/qtquick-porting-qt5.html) for details.

**Comment by LubosD** [comment]
This is definitely planned and should be very easy. The only reason why QtQuick 1 was chosen was to make at least one Qt4-compatible release.

**Comment by mkubecek** [comment]
I suggest to fork a stable-1.9 branch at dcd1d23d6d49 for "bugfix only" 1.9.x releases so that master can be used for more intrusive changes (like this one).

**Comment by LubosD** [comment]
Done.

**Comment by mitya57** [comment]
Thanks for the quick fix!
