### ISSUE TITLE
credentials aren't read?

### ISSUE THREAD

**Issue by oliver-cfc** [LubosD/twinkle#62]
When I start up twinkle it asks me to re-enter my credentials (auth-user and auth-password) and then the phone registers.  I see them (in plain text) in the .cfg file so why doesn't twinkle pass them on automatically?  Is there some sort of keyring requirement?

**Comment by LubosD** [comment]
No, I never had to re-enter them, unless the stored ones are rejected by the proxy.

**Comment by oliver-cfc** [comment]
You're right.  I started again with a clean environment and all is good.  Sorry for the noise and thanks for bringing Twinkle back :-)
