### ISSUE TITLE
call list sorting alphanumerical

### ISSUE THREAD

**Issue by bosso73** [LubosD/twinkle#69]
Sorting of the calling list by date/time is currently accomplished alphanumerically, which obviously does not work, unless the entries are in the ISO-form YYYY-MM-DD HH:MM:SS; sorting should be done by time() -- seconds since 1970 or something.

**Comment by fbriere** [comment]
This bug had already been fixed last year by #32; the "time" column is now converted to `QDateTime`, and Qt handles the sorting/formatting automatically.

You can confirm this by running Twinkle under a locale that formats dates as `d/mm/yyyy`, such as `en_AU`, like this: `LC_TIME=en_AU.UTF-8 twinkle`.  You will see that `30/09/2016` properly sorts before `1/10/2016`, which would not be the case in an alphanumerical sort.
