### ISSUE TITLE
twinkle hangs when it receives REFER and pops up transfer window

### ISSUE THREAD

**Issue by juha-h** [LubosD/twinkle#74]
I gave Twinkle 1:1.10.0+dfsg-1~bpo8+1 from Debian jessie backports a try.

When twinkle receives REFER it pops up a window asking (Yes/No) permission for the call
transfer.  Unfortunately at that point twinkle hangs and Yes/No buttons
are not responsive.  At that point, twinkle reports to console:

QObject::setParent: Cannot set parent, new parent is in a different thread
QLayout: Attempting to add QLayout "" to YesNoDialog "", which already has a layout
QObject::connect: Cannot queue arguments of type 'QTextBlock'
(Make sure 'QTextBlock' is registered using qRegisterMetaType().)

Regards,

-- Juha

**Comment by fbriere** [comment]
Could you give fbriere/twinkle@b55a543379baf0aee38d85ec7cf819669bbe13b2 a whirl?  I think I have fixed this issue, but I lack the means to actually test it.  Any feedback would therefore be quite appreciated.  :smile:

I can also provide you with a Debian binary package (amd64 or i386) if this makes things easier for you.

**Comment by juha-h** [comment]
Fr�d�ric Bri�re writes:

> Could you give
> fbriere/twinkle@b55a543379baf0aee38d85ec7cf819669bbe13b2 a whirl?  I
> think I have fixed this issue, but I lack the means to actually test
> it.  Any feedback would therefore be quite appreciated.  :smile: 
> 
> I can also provide you with a Debian binary package (amd64 or i386) if
> this makes things easier for you.

Thanks for the patch.  Since github repo does not include debian dir, I
would appreciate if you could put amd64 package somewhere to download.

-- Juha

**Comment by LubosD** [comment]
I suspect there could be trouble with the patch. I think the best way is to convert all those std::string and t_url parameters to plain QStrings and pass that instead.

**Comment by fbriere** [comment]
My bad, `t_url` is indeed not a registered datatype, and will cause a runtime error if passed as-is to `invokeMethod()`.  I had blindly copied the fix from `cb_ask_user_to_redirect_{invite,request}()`, not realizing that those were `BlockingQueuedConnection`, and therefore had looser requirements.  (It's been a long time since I last played with Qt.  :smile:)

`std::string` is registered, though (probably implicitly, through `std::list<std::string>`).  Unless you object, passing those around instead of `QString` would probably keep things simpler, especially since (unless I'm mistaken) converting between `t_url` and `QString` still requires `std::string` as a middle step.

**Comment by LubosD** [comment]
OK!

**Comment by fbriere** [comment]
Debian binary packages for jessie/amd64 with 582abb4 applied have been uploaded to https://github.com/fbriere/twinkle/tree/issue/74-freeze-on-refer.deb.

**Comment by juha-h** [comment]
I gave twinkle_1.10.0+dfsg-1~bpo8+2~1.gbp5f817b_amd64.deb a try.  I have 
in SIP protocol:

x Accept call transfer request (incoming REFER)
x Ask user permission to transfer

When REFER arrives, no confirmation window appears.  Instead, I get to
console:

qrc:/qml/incoming_call.qml:38:5: QML TextImageButton: Binding loop detected for property "color"
warning: The VAD has been replaced by a hack pending a complete rewrite
QMetaMethod::invoke: Unable to handle unregistered datatype 'const string&'

-- Juha

**Comment by fbriere** [comment]
Drat, I could have *sworn* I had successfully tried passing a `std::string` before.  On further testing, it seems that I was indeed wrong.  (Registering `std::list<T>` does not appear to register `T` after all.  Besides, `string` and `std::string` are not seen as equivalent by Qt.)

Properly registering `string` does the trick.  (Even though I cannot test the REFER itself, it occurred to be that I could at least test the pop-up itself.)  New Debian packages have been uploaded.

**Comment by juha-h** [comment]
Fr�d�ric Bri�re writes:

> Properly registering `string` does the trick.  (Even though I cannot
> test the REFER itself, it occurred to be that I could at least test
> the pop-up itself.)  New Debian packages have been uploaded.

Now REFER popup and confirmation click work fine.  Thanks, Juha
