### ISSUE TITLE
compiler configuration/dependencies on Ubuntu 16.04

### ISSUE THREAD

**Issue by davekimble2** [LubosD/twinkle#91]
In a perfectly ordinary Ubuntu 16.04 (64), cmake fails to find **libmagic**, but it is in the same directory where is just found **libxml2** .  I'm stuck.

```
$ git clone https://github.com/LubosD/twinkle.git
$ cd twinkle
$ mkdir build
$ cd build
$ cmake .. -DWITH_ALSA=On -DWITH_SPEEX=On -DWITH_ILBC=On -DWITH_ZRTP=On -DWITH_G729=On -DWITH_QT5=On
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found LibXml2: /usr/lib/x86_64-linux-gnu/libxml2.so (found version "2.9.3") 
-- libmagic version: 5.25
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find LibMagic (missing: LibMagic_LIBRARY LibMagic_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLibMagic.cmake:61 (find_package_handle_standard_args)
  CMakeLists.txt:24 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/****/twinkle/build/CMakeFiles/CMakeOutput.log".
$ locate libmagic
...
/usr/lib/x86_64-linux-gnu/libmagic.so.1
/usr/lib/x86_64-linux-gnu/libmagic.so.1.0.0
...
$
```

**Comment by LubosD** [comment]
Having the .so is one thing, but have you installed the header files?

**Comment by davekimble2** [comment]
I don't know - I've never heard of libmagic before.  I'm just following the instructions.  Please tell me how to check and fix.

**Comment by LubosD** [comment]
Please, before you start compiling software on your own, spend some time getting to know things. This is quite elementary.

Install libmagic-dev and this should be taken care of.

**Comment by davekimble2** [comment]
Pardon my ignorance, but aren't **you** supposed to list all the dependencies that need to be installed first (perhaps many of which I will already have).  Then after installing a long list of stuff, make/cmake sails through OK.  I'm right out of my depth here.

```
$ sudo apt install libmagic-dev
$ cmake .. -DWITH_ALSA=On -DWITH_SPEEX=On -DWITH_ILBC=On -DWITH_ZRTP=On -DWITH_G729=On -DWITH_QT5=On
-- libmagic version: 5.25
-- Found LibMagic: /usr/lib/x86_64-linux-gnu/libmagic.so  
CMake Error at cmake/FindLibSndfile.cmake:16 (MESSAGE):
  Could not find sndfile
Call Stack (most recent call first):
  CMakeLists.txt:25 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/****/twinkle/build/CMakeFiles/CMakeOutput.log".
$
```

**Comment by mkubecek** [comment]
You can hardly expect upstream maintainer to research all existing distributions (there are tens or perhaps rather hundreds of those) and provide list of exact names of devel packages in each of them (which may even vary with version of the distribution). I'm afraid Luboš is perfectly right: if you don't know you need a devel package for library you are compiling against and don't know how to find it, you will have problems compiling virtually anything from source.

As for your latest output, I suppose your problem is that you tried to install "sendfile-dev" instead of "sndfile-dev" ("snd" here stands for "sound", not "send"). The package may be also called libsndfile(-dev)  as some distributions have (reasonable, IMHO) rule that names of library packages should always start with "lib".

**Comment by davekimble2** [comment]
Thanks.  I'm surprised at that - surely the developer knows what is being called from libraries, that would be a start, and I suppose somewhere must say what the Ubuntu libraries are actually called.  Anyway, I tried installing **libsndfile-dev**, and the installer didn't have it but suggested **libsndfle1-dev**, so I was able to force my way on to **readline**, **bison**, **flex**, **ucommon**, **ccrtp**, **libqt5widgets** and there I got stuck with:
```
CMake Error at CMakeLists.txt:34 (find_package):
By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Widgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Widgets" with
  any of the following names:

    Qt5WidgetsConfig.cmake
    qt5widgets-config.cmake

  Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
  "Qt5Widgets_DIR" to a directory containing one of the above files.  If
  "Qt5Widgets" provides a separate development package or SDK, be sure it has
  been installed.
```

I did find this exact problem elsewhere, and the "solution" given was to install a whole bunch of stuff:

http://avidemux.org/smif/index.php?topic=16948.0
sudo apt-get install libasound2-dev libdca-dev libfontconfig1-dev libfribidi-dev libmad0-dev libogg-dev libopencore-amrnb-dev libopencore-amrwb-dev libopus-dev libpulse-dev libtwolame-dev libva-dev vainfo libvdpau-dev vdpauinfo libvorbis-dev libvpx-dev libx265-dev x265 libxv-dev libxvidcore-dev libzip-dev nvidia-cuda-toolkit

but that involves downloading 727 MB of compressed packages - all to get a lousy .cmake file.

There's got to be a better way than is.

**Comment by LubosD** [comment]
The developer doesn't know the exact package names on your distribution. But firstly you need to learn the difference between ordinary and -dev(el) packages. Non-devel packages will not fix a cmake/configure/whatever problem for you, because devel packages are in general what you need for a build. So obviously installing libqt5widgets won't fix the problem.

**Comment by davekimble2** [comment]
Thanks.  I'm surprised at that - surely the developer knows what is being called from libraries, that would be a start, and I suppose somewhere must say what the Ubuntu libraries are actually called.  Anyway, I tried installing **libsndfile-dev**, and the installer didn't have it but suggested **libsndfle1-dev**, so I was able to force my way on to **readline**, **bison**, **flex**, **ucommon**, **ccrtp**, **libqt5widgets** and there I got stuck with:
```
CMake Error at CMakeLists.txt:34 (find_package):
By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Widgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Widgets" with
  any of the following names:

    Qt5WidgetsConfig.cmake
    qt5widgets-config.cmake

  Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
  "Qt5Widgets_DIR" to a directory containing one of the above files.  If
  "Qt5Widgets" provides a separate development package or SDK, be sure it has
  been installed.
```

Surely there must be a better way to do this.  I see I have compiled 36 other applications and never had this problem at all.

**Comment by davekimble2** [comment]
Yes, I've understood that since you first said it.  I still can't find anything to satisfy this latest "not found".  The Ubuntu package is called libqt5widgets5, and I've got it installed, so apparently for a build I want libqt5widgets5-dev , but it doesn't exist in Ubuntu's repository.  That's not your fault, but is that the end of the matter? - no Twinkle-1.10.0 on Ubuntu, which has 70% of the Linux market?

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
just compile qt5base with cmake
