### ISSUE TITLE
PAI header when hiding identity

### ISSUE THREAD

**Issue by gwozniak** [LubosD/twinkle#93]
Hi,
I needed  PAI header for testing sip media server in my job. 
I've added option for sending P-Asserted-Identity when calling with anonymous user (Hide identity in call dialog box) to sources, after compilation it works nice.
All work was rewrite of PPI header option.
It looks like that: 
![image](https://cloud.githubusercontent.com/assets/848953/24933578/45ddcc46-1f17-11e7-9a95-f0df13a5007e.png)

Could I do pull req ?

**Comment by LubosD** [comment]
OK!

**Comment by fbriere** [comment]
From what I understand, this issue was resolved by PR #94.
