### ISSUE TITLE
Entering DTMF 3 with keyboard results in double presses

### ISSUE THREAD

**Issue by chewi** [LubosD/twinkle#95]
This is an odd one. If you enter DTMF 3 using the keyboard then you get a double press but only if the DTMF window is focused. It doesn't happen if you key into the "display" window instead and it doesn't happen if you press the 3 button with the mouse. None of the other DTMF keys seem to be affected.

Great to see this project back after so many years! I've still got an e-mail exchange with Michel about ALSA from late 2005. I've been really sick of buggy Ekiga and Ring/SFLPhone went from being quite decent to completely unusable within a few months.

**Comment by LubosD** [comment]
Thanks for your report, fixed!
