### ISSUE TITLE
Not receiving calls

### ISSUE THREAD

**Issue by jalalsfs** [LubosD/twinkle#96]
Hi, I am using Twinkle 1.10.1 - 07 October 2016 in Fedora 26, I can do calling from Twinkle to any other devices, but when I call from any device to Twinkle, nothing appear, no ringing nor notification.
Hope it can be solved soon.
Thanks

**Comment by fbriere** [comment]
Do you see anything in the Twinkle log when an incoming call is attempted?

My guess is that this is a networking issue (NAT-related, probably), and that Twinkle does not receive any data to react to in the first place.  Unfortunately, there's not much anyone can do without being familiar with your particular networking setup.

For more information on this, see the [NAT section in the README](https://github.com/LubosD/twinkle#nat), or the [NAT traversal section in the old manual](https://mfnboer.home.xs4all.nl/twinkle/manual.html#nat_traversal).

**Comment by fbriere** [comment]
Closing in the absence of a response.
